displayName=Price Paid
author=aidanmastro
description=Tracks what you paid for items on the GE and how their value has changed since
tags=ge,grand,exchange,tracker,tracking,item,items,paid,cost,bought,purchase,purchases,price,prices,value,gear
plugins=com.pricepaid.PricePaidPlugin
build=standard
version=1.0.0
